Fix tests (#4)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -21,8 +21,19 @@ jobs:
           printf '#!/bin/bash\n' > run.sh
           yq '.runs[].0.run' < action.yaml >> run.sh
           chmod +x run.sh
-          RUN=$(readlink -fem run.sh)
-          find .github/workflows/tests -name "*.sh" -type f -exec sh -c 'printf "Testing %s ...\n" "$(basename $1 ".sh")"; sh .github/workflows/test-wrapper.sh "$1" "$2"' -- {} "$RUN" \;
+          find .github/workflows/tests -type f -name '*.[sS][hH]' -exec sh -c '
+            for file do
+              printf "Testing %s ...\n" "$(basename $file ".sh")"
+              if ! sh .github/workflows/test-wrapper.sh "$file" run.sh; then
+                kill -s PIPE "$PPID"
+                exit 1
+              fi
+            done' sh {} +
+
+          [ $? -eq 0 ] || {
+              echo "Tests failed!"
+              exit 1
+          }
 
   shellcheck:
     name: Shellcheck
